//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWsApi.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webapi.glareled.net/", ConfigurationName="ServiceReference1.GLSysMgrSoap")]
    public interface GLSysMgrSoap {
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SuperLogin", ReplyAction="*")]
        TestWsApi.ServiceReference1.SuperLoginResponse SuperLogin(TestWsApi.ServiceReference1.SuperLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SuperLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SuperLoginResponse> SuperLoginAsync(TestWsApi.ServiceReference1.SuperLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SuperLoginHtml", ReplyAction="*")]
        void SuperLoginHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SuperLoginHtml", ReplyAction="*")]
        System.Threading.Tasks.Task SuperLoginHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/OrgLogin", ReplyAction="*")]
        TestWsApi.ServiceReference1.OrgLoginResponse OrgLogin(TestWsApi.ServiceReference1.OrgLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/OrgLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.OrgLoginResponse> OrgLoginAsync(TestWsApi.ServiceReference1.OrgLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/OrgLoginHtml", ReplyAction="*")]
        void OrgLoginHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/OrgLoginHtml", ReplyAction="*")]
        System.Threading.Tasks.Task OrgLoginHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/Projectlogin", ReplyAction="*")]
        TestWsApi.ServiceReference1.ProjectloginResponse Projectlogin(TestWsApi.ServiceReference1.ProjectloginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/Projectlogin", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.ProjectloginResponse> ProjectloginAsync(TestWsApi.ServiceReference1.ProjectloginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/ProjectloginHtml", ReplyAction="*")]
        void ProjectloginHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/ProjectloginHtml", ReplyAction="*")]
        System.Threading.Tasks.Task ProjectloginHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/Logout", ReplyAction="*")]
        TestWsApi.ServiceReference1.LogoutResponse Logout(TestWsApi.ServiceReference1.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.LogoutResponse> LogoutAsync(TestWsApi.ServiceReference1.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/LogoutHtml", ReplyAction="*")]
        void LogoutHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/LogoutHtml", ReplyAction="*")]
        System.Threading.Tasks.Task LogoutHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/UpdateLoginTimeByUuid", ReplyAction="*")]
        TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse UpdateLoginTimeByUuid(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/UpdateLoginTimeByUuid", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse> UpdateLoginTimeByUuidAsync(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/UpdateLoginTimeByUuidHtml", ReplyAction="*")]
        void UpdateLoginTimeByUuidHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/UpdateLoginTimeByUuidHtml", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateLoginTimeByUuidHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SetCmdToDb", ReplyAction="*")]
        TestWsApi.ServiceReference1.SetCmdToDbResponse SetCmdToDb(TestWsApi.ServiceReference1.SetCmdToDbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/SetCmdToDb", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SetCmdToDbResponse> SetCmdToDbAsync(TestWsApi.ServiceReference1.SetCmdToDbRequest request);
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strJsonParam 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/GetAllProject", ReplyAction="*")]
        TestWsApi.ServiceReference1.GetAllProjectResponse GetAllProject(TestWsApi.ServiceReference1.GetAllProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/GetAllProject", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.GetAllProjectResponse> GetAllProjectAsync(TestWsApi.ServiceReference1.GetAllProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/GetAllProjectHtml", ReplyAction="*")]
        void GetAllProjectHtml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/GetAllProjectHtml", ReplyAction="*")]
        System.Threading.Tasks.Task GetAllProjectHtmlAsync();
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddNewOrg", ReplyAction="*")]
        TestWsApi.ServiceReference1.AddNewOrgResponse AddNewOrg(TestWsApi.ServiceReference1.AddNewOrgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddNewOrg", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddNewOrgResponse> AddNewOrgAsync(TestWsApi.ServiceReference1.AddNewOrgRequest request);
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddGroup", ReplyAction="*")]
        TestWsApi.ServiceReference1.AddGroupResponse AddGroup(TestWsApi.ServiceReference1.AddGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddGroupResponse> AddGroupAsync(TestWsApi.ServiceReference1.AddGroupRequest request);
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddProject", ReplyAction="*")]
        TestWsApi.ServiceReference1.AddProjectResponse AddProject(TestWsApi.ServiceReference1.AddProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddProject", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddProjectResponse> AddProjectAsync(TestWsApi.ServiceReference1.AddProjectRequest request);
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddSuperUser", ReplyAction="*")]
        TestWsApi.ServiceReference1.AddSuperUserResponse AddSuperUser(TestWsApi.ServiceReference1.AddSuperUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddSuperUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddSuperUserResponse> AddSuperUserAsync(TestWsApi.ServiceReference1.AddSuperUserRequest request);
        
        // CODEGEN: 命名空间 http://webapi.glareled.net/ 的元素名称 strParams 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddOrgUser", ReplyAction="*")]
        TestWsApi.ServiceReference1.AddOrgUserResponse AddOrgUser(TestWsApi.ServiceReference1.AddOrgUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webapi.glareled.net/AddOrgUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddOrgUserResponse> AddOrgUserAsync(TestWsApi.ServiceReference1.AddOrgUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuperLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuperLogin", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.SuperLoginRequestBody Body;
        
        public SuperLoginRequest() {
        }
        
        public SuperLoginRequest(TestWsApi.ServiceReference1.SuperLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class SuperLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public SuperLoginRequestBody() {
        }
        
        public SuperLoginRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SuperLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SuperLoginResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.SuperLoginResponseBody Body;
        
        public SuperLoginResponse() {
        }
        
        public SuperLoginResponse(TestWsApi.ServiceReference1.SuperLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class SuperLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SuperLoginResult;
        
        public SuperLoginResponseBody() {
        }
        
        public SuperLoginResponseBody(string SuperLoginResult) {
            this.SuperLoginResult = SuperLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrgLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrgLogin", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.OrgLoginRequestBody Body;
        
        public OrgLoginRequest() {
        }
        
        public OrgLoginRequest(TestWsApi.ServiceReference1.OrgLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class OrgLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public OrgLoginRequestBody() {
        }
        
        public OrgLoginRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OrgLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OrgLoginResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.OrgLoginResponseBody Body;
        
        public OrgLoginResponse() {
        }
        
        public OrgLoginResponse(TestWsApi.ServiceReference1.OrgLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class OrgLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrgLoginResult;
        
        public OrgLoginResponseBody() {
        }
        
        public OrgLoginResponseBody(string OrgLoginResult) {
            this.OrgLoginResult = OrgLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProjectloginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Projectlogin", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.ProjectloginRequestBody Body;
        
        public ProjectloginRequest() {
        }
        
        public ProjectloginRequest(TestWsApi.ServiceReference1.ProjectloginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class ProjectloginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public ProjectloginRequestBody() {
        }
        
        public ProjectloginRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProjectloginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProjectloginResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.ProjectloginResponseBody Body;
        
        public ProjectloginResponse() {
        }
        
        public ProjectloginResponse(TestWsApi.ServiceReference1.ProjectloginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class ProjectloginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProjectloginResult;
        
        public ProjectloginResponseBody() {
        }
        
        public ProjectloginResponseBody(string ProjectloginResult) {
            this.ProjectloginResult = ProjectloginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logout", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.LogoutRequestBody Body;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(TestWsApi.ServiceReference1.LogoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class LogoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public LogoutRequestBody() {
        }
        
        public LogoutRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.LogoutResponseBody Body;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(TestWsApi.ServiceReference1.LogoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class LogoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogoutResult;
        
        public LogoutResponseBody() {
        }
        
        public LogoutResponseBody(string LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLoginTimeByUuidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLoginTimeByUuid", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequestBody Body;
        
        public UpdateLoginTimeByUuidRequest() {
        }
        
        public UpdateLoginTimeByUuidRequest(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class UpdateLoginTimeByUuidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public UpdateLoginTimeByUuidRequestBody() {
        }
        
        public UpdateLoginTimeByUuidRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLoginTimeByUuidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLoginTimeByUuidResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponseBody Body;
        
        public UpdateLoginTimeByUuidResponse() {
        }
        
        public UpdateLoginTimeByUuidResponse(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class UpdateLoginTimeByUuidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateLoginTimeByUuidResult;
        
        public UpdateLoginTimeByUuidResponseBody() {
        }
        
        public UpdateLoginTimeByUuidResponseBody(string UpdateLoginTimeByUuidResult) {
            this.UpdateLoginTimeByUuidResult = UpdateLoginTimeByUuidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCmdToDbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCmdToDb", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.SetCmdToDbRequestBody Body;
        
        public SetCmdToDbRequest() {
        }
        
        public SetCmdToDbRequest(TestWsApi.ServiceReference1.SetCmdToDbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class SetCmdToDbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public SetCmdToDbRequestBody() {
        }
        
        public SetCmdToDbRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCmdToDbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetCmdToDbResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.SetCmdToDbResponseBody Body;
        
        public SetCmdToDbResponse() {
        }
        
        public SetCmdToDbResponse(TestWsApi.ServiceReference1.SetCmdToDbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class SetCmdToDbResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetCmdToDbResult;
        
        public SetCmdToDbResponseBody() {
        }
        
        public SetCmdToDbResponseBody(string SetCmdToDbResult) {
            this.SetCmdToDbResult = SetCmdToDbResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProject", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.GetAllProjectRequestBody Body;
        
        public GetAllProjectRequest() {
        }
        
        public GetAllProjectRequest(TestWsApi.ServiceReference1.GetAllProjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class GetAllProjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strJsonParam;
        
        public GetAllProjectRequestBody() {
        }
        
        public GetAllProjectRequestBody(string strJsonParam) {
            this.strJsonParam = strJsonParam;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProjectResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.GetAllProjectResponseBody Body;
        
        public GetAllProjectResponse() {
        }
        
        public GetAllProjectResponse(TestWsApi.ServiceReference1.GetAllProjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class GetAllProjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllProjectResult;
        
        public GetAllProjectResponseBody() {
        }
        
        public GetAllProjectResponseBody(string GetAllProjectResult) {
            this.GetAllProjectResult = GetAllProjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewOrgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewOrg", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddNewOrgRequestBody Body;
        
        public AddNewOrgRequest() {
        }
        
        public AddNewOrgRequest(TestWsApi.ServiceReference1.AddNewOrgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddNewOrgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public AddNewOrgRequestBody() {
        }
        
        public AddNewOrgRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewOrgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewOrgResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddNewOrgResponseBody Body;
        
        public AddNewOrgResponse() {
        }
        
        public AddNewOrgResponse(TestWsApi.ServiceReference1.AddNewOrgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddNewOrgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewOrgResult;
        
        public AddNewOrgResponseBody() {
        }
        
        public AddNewOrgResponseBody(string AddNewOrgResult) {
            this.AddNewOrgResult = AddNewOrgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGroup", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddGroupRequestBody Body;
        
        public AddGroupRequest() {
        }
        
        public AddGroupRequest(TestWsApi.ServiceReference1.AddGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public AddGroupRequestBody() {
        }
        
        public AddGroupRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGroupResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddGroupResponseBody Body;
        
        public AddGroupResponse() {
        }
        
        public AddGroupResponse(TestWsApi.ServiceReference1.AddGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddGroupResult;
        
        public AddGroupResponseBody() {
        }
        
        public AddGroupResponseBody(string AddGroupResult) {
            this.AddGroupResult = AddGroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProject", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddProjectRequestBody Body;
        
        public AddProjectRequest() {
        }
        
        public AddProjectRequest(TestWsApi.ServiceReference1.AddProjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddProjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public AddProjectRequestBody() {
        }
        
        public AddProjectRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProjectResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddProjectResponseBody Body;
        
        public AddProjectResponse() {
        }
        
        public AddProjectResponse(TestWsApi.ServiceReference1.AddProjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddProjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddProjectResult;
        
        public AddProjectResponseBody() {
        }
        
        public AddProjectResponseBody(string AddProjectResult) {
            this.AddProjectResult = AddProjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSuperUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSuperUser", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddSuperUserRequestBody Body;
        
        public AddSuperUserRequest() {
        }
        
        public AddSuperUserRequest(TestWsApi.ServiceReference1.AddSuperUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddSuperUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public AddSuperUserRequestBody() {
        }
        
        public AddSuperUserRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSuperUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSuperUserResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddSuperUserResponseBody Body;
        
        public AddSuperUserResponse() {
        }
        
        public AddSuperUserResponse(TestWsApi.ServiceReference1.AddSuperUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddSuperUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSuperUserResult;
        
        public AddSuperUserResponseBody() {
        }
        
        public AddSuperUserResponseBody(string AddSuperUserResult) {
            this.AddSuperUserResult = AddSuperUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrgUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrgUser", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddOrgUserRequestBody Body;
        
        public AddOrgUserRequest() {
        }
        
        public AddOrgUserRequest(TestWsApi.ServiceReference1.AddOrgUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddOrgUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strParams;
        
        public AddOrgUserRequestBody() {
        }
        
        public AddOrgUserRequestBody(string strParams) {
            this.strParams = strParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrgUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrgUserResponse", Namespace="http://webapi.glareled.net/", Order=0)]
        public TestWsApi.ServiceReference1.AddOrgUserResponseBody Body;
        
        public AddOrgUserResponse() {
        }
        
        public AddOrgUserResponse(TestWsApi.ServiceReference1.AddOrgUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://webapi.glareled.net/")]
    public partial class AddOrgUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOrgUserResult;
        
        public AddOrgUserResponseBody() {
        }
        
        public AddOrgUserResponseBody(string AddOrgUserResult) {
            this.AddOrgUserResult = AddOrgUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GLSysMgrSoapChannel : TestWsApi.ServiceReference1.GLSysMgrSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GLSysMgrSoapClient : System.ServiceModel.ClientBase<TestWsApi.ServiceReference1.GLSysMgrSoap>, TestWsApi.ServiceReference1.GLSysMgrSoap {
        
        public GLSysMgrSoapClient() {
        }
        
        public GLSysMgrSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GLSysMgrSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GLSysMgrSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GLSysMgrSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.SuperLoginResponse TestWsApi.ServiceReference1.GLSysMgrSoap.SuperLogin(TestWsApi.ServiceReference1.SuperLoginRequest request) {
            return base.Channel.SuperLogin(request);
        }
        
        public string SuperLogin(string strJsonParam) {
            TestWsApi.ServiceReference1.SuperLoginRequest inValue = new TestWsApi.ServiceReference1.SuperLoginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.SuperLoginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.SuperLoginResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).SuperLogin(inValue);
            return retVal.Body.SuperLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SuperLoginResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.SuperLoginAsync(TestWsApi.ServiceReference1.SuperLoginRequest request) {
            return base.Channel.SuperLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SuperLoginResponse> SuperLoginAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.SuperLoginRequest inValue = new TestWsApi.ServiceReference1.SuperLoginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.SuperLoginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).SuperLoginAsync(inValue);
        }
        
        public void SuperLoginHtml() {
            base.Channel.SuperLoginHtml();
        }
        
        public System.Threading.Tasks.Task SuperLoginHtmlAsync() {
            return base.Channel.SuperLoginHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.OrgLoginResponse TestWsApi.ServiceReference1.GLSysMgrSoap.OrgLogin(TestWsApi.ServiceReference1.OrgLoginRequest request) {
            return base.Channel.OrgLogin(request);
        }
        
        public string OrgLogin(string strJsonParam) {
            TestWsApi.ServiceReference1.OrgLoginRequest inValue = new TestWsApi.ServiceReference1.OrgLoginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.OrgLoginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.OrgLoginResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).OrgLogin(inValue);
            return retVal.Body.OrgLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.OrgLoginResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.OrgLoginAsync(TestWsApi.ServiceReference1.OrgLoginRequest request) {
            return base.Channel.OrgLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.OrgLoginResponse> OrgLoginAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.OrgLoginRequest inValue = new TestWsApi.ServiceReference1.OrgLoginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.OrgLoginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).OrgLoginAsync(inValue);
        }
        
        public void OrgLoginHtml() {
            base.Channel.OrgLoginHtml();
        }
        
        public System.Threading.Tasks.Task OrgLoginHtmlAsync() {
            return base.Channel.OrgLoginHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.ProjectloginResponse TestWsApi.ServiceReference1.GLSysMgrSoap.Projectlogin(TestWsApi.ServiceReference1.ProjectloginRequest request) {
            return base.Channel.Projectlogin(request);
        }
        
        public string Projectlogin(string strJsonParam) {
            TestWsApi.ServiceReference1.ProjectloginRequest inValue = new TestWsApi.ServiceReference1.ProjectloginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.ProjectloginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.ProjectloginResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).Projectlogin(inValue);
            return retVal.Body.ProjectloginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.ProjectloginResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.ProjectloginAsync(TestWsApi.ServiceReference1.ProjectloginRequest request) {
            return base.Channel.ProjectloginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.ProjectloginResponse> ProjectloginAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.ProjectloginRequest inValue = new TestWsApi.ServiceReference1.ProjectloginRequest();
            inValue.Body = new TestWsApi.ServiceReference1.ProjectloginRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).ProjectloginAsync(inValue);
        }
        
        public void ProjectloginHtml() {
            base.Channel.ProjectloginHtml();
        }
        
        public System.Threading.Tasks.Task ProjectloginHtmlAsync() {
            return base.Channel.ProjectloginHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.LogoutResponse TestWsApi.ServiceReference1.GLSysMgrSoap.Logout(TestWsApi.ServiceReference1.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public string Logout(string strJsonParam) {
            TestWsApi.ServiceReference1.LogoutRequest inValue = new TestWsApi.ServiceReference1.LogoutRequest();
            inValue.Body = new TestWsApi.ServiceReference1.LogoutRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.LogoutResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).Logout(inValue);
            return retVal.Body.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.LogoutResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.LogoutAsync(TestWsApi.ServiceReference1.LogoutRequest request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.LogoutResponse> LogoutAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.LogoutRequest inValue = new TestWsApi.ServiceReference1.LogoutRequest();
            inValue.Body = new TestWsApi.ServiceReference1.LogoutRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).LogoutAsync(inValue);
        }
        
        public void LogoutHtml() {
            base.Channel.LogoutHtml();
        }
        
        public System.Threading.Tasks.Task LogoutHtmlAsync() {
            return base.Channel.LogoutHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse TestWsApi.ServiceReference1.GLSysMgrSoap.UpdateLoginTimeByUuid(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest request) {
            return base.Channel.UpdateLoginTimeByUuid(request);
        }
        
        public string UpdateLoginTimeByUuid(string strJsonParam) {
            TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest inValue = new TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest();
            inValue.Body = new TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).UpdateLoginTimeByUuid(inValue);
            return retVal.Body.UpdateLoginTimeByUuidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.UpdateLoginTimeByUuidAsync(TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest request) {
            return base.Channel.UpdateLoginTimeByUuidAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.UpdateLoginTimeByUuidResponse> UpdateLoginTimeByUuidAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest inValue = new TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequest();
            inValue.Body = new TestWsApi.ServiceReference1.UpdateLoginTimeByUuidRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).UpdateLoginTimeByUuidAsync(inValue);
        }
        
        public void UpdateLoginTimeByUuidHtml() {
            base.Channel.UpdateLoginTimeByUuidHtml();
        }
        
        public System.Threading.Tasks.Task UpdateLoginTimeByUuidHtmlAsync() {
            return base.Channel.UpdateLoginTimeByUuidHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.SetCmdToDbResponse TestWsApi.ServiceReference1.GLSysMgrSoap.SetCmdToDb(TestWsApi.ServiceReference1.SetCmdToDbRequest request) {
            return base.Channel.SetCmdToDb(request);
        }
        
        public string SetCmdToDb(string strParams) {
            TestWsApi.ServiceReference1.SetCmdToDbRequest inValue = new TestWsApi.ServiceReference1.SetCmdToDbRequest();
            inValue.Body = new TestWsApi.ServiceReference1.SetCmdToDbRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.SetCmdToDbResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).SetCmdToDb(inValue);
            return retVal.Body.SetCmdToDbResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SetCmdToDbResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.SetCmdToDbAsync(TestWsApi.ServiceReference1.SetCmdToDbRequest request) {
            return base.Channel.SetCmdToDbAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.SetCmdToDbResponse> SetCmdToDbAsync(string strParams) {
            TestWsApi.ServiceReference1.SetCmdToDbRequest inValue = new TestWsApi.ServiceReference1.SetCmdToDbRequest();
            inValue.Body = new TestWsApi.ServiceReference1.SetCmdToDbRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).SetCmdToDbAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.GetAllProjectResponse TestWsApi.ServiceReference1.GLSysMgrSoap.GetAllProject(TestWsApi.ServiceReference1.GetAllProjectRequest request) {
            return base.Channel.GetAllProject(request);
        }
        
        public string GetAllProject(string strJsonParam) {
            TestWsApi.ServiceReference1.GetAllProjectRequest inValue = new TestWsApi.ServiceReference1.GetAllProjectRequest();
            inValue.Body = new TestWsApi.ServiceReference1.GetAllProjectRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            TestWsApi.ServiceReference1.GetAllProjectResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).GetAllProject(inValue);
            return retVal.Body.GetAllProjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.GetAllProjectResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.GetAllProjectAsync(TestWsApi.ServiceReference1.GetAllProjectRequest request) {
            return base.Channel.GetAllProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.GetAllProjectResponse> GetAllProjectAsync(string strJsonParam) {
            TestWsApi.ServiceReference1.GetAllProjectRequest inValue = new TestWsApi.ServiceReference1.GetAllProjectRequest();
            inValue.Body = new TestWsApi.ServiceReference1.GetAllProjectRequestBody();
            inValue.Body.strJsonParam = strJsonParam;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).GetAllProjectAsync(inValue);
        }
        
        public void GetAllProjectHtml() {
            base.Channel.GetAllProjectHtml();
        }
        
        public System.Threading.Tasks.Task GetAllProjectHtmlAsync() {
            return base.Channel.GetAllProjectHtmlAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.AddNewOrgResponse TestWsApi.ServiceReference1.GLSysMgrSoap.AddNewOrg(TestWsApi.ServiceReference1.AddNewOrgRequest request) {
            return base.Channel.AddNewOrg(request);
        }
        
        public string AddNewOrg(string strParams) {
            TestWsApi.ServiceReference1.AddNewOrgRequest inValue = new TestWsApi.ServiceReference1.AddNewOrgRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddNewOrgRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.AddNewOrgResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddNewOrg(inValue);
            return retVal.Body.AddNewOrgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddNewOrgResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.AddNewOrgAsync(TestWsApi.ServiceReference1.AddNewOrgRequest request) {
            return base.Channel.AddNewOrgAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddNewOrgResponse> AddNewOrgAsync(string strParams) {
            TestWsApi.ServiceReference1.AddNewOrgRequest inValue = new TestWsApi.ServiceReference1.AddNewOrgRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddNewOrgRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddNewOrgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.AddGroupResponse TestWsApi.ServiceReference1.GLSysMgrSoap.AddGroup(TestWsApi.ServiceReference1.AddGroupRequest request) {
            return base.Channel.AddGroup(request);
        }
        
        public string AddGroup(string strParams) {
            TestWsApi.ServiceReference1.AddGroupRequest inValue = new TestWsApi.ServiceReference1.AddGroupRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddGroupRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.AddGroupResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddGroup(inValue);
            return retVal.Body.AddGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddGroupResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.AddGroupAsync(TestWsApi.ServiceReference1.AddGroupRequest request) {
            return base.Channel.AddGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddGroupResponse> AddGroupAsync(string strParams) {
            TestWsApi.ServiceReference1.AddGroupRequest inValue = new TestWsApi.ServiceReference1.AddGroupRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddGroupRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.AddProjectResponse TestWsApi.ServiceReference1.GLSysMgrSoap.AddProject(TestWsApi.ServiceReference1.AddProjectRequest request) {
            return base.Channel.AddProject(request);
        }
        
        public string AddProject(string strParams) {
            TestWsApi.ServiceReference1.AddProjectRequest inValue = new TestWsApi.ServiceReference1.AddProjectRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddProjectRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.AddProjectResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddProject(inValue);
            return retVal.Body.AddProjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddProjectResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.AddProjectAsync(TestWsApi.ServiceReference1.AddProjectRequest request) {
            return base.Channel.AddProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddProjectResponse> AddProjectAsync(string strParams) {
            TestWsApi.ServiceReference1.AddProjectRequest inValue = new TestWsApi.ServiceReference1.AddProjectRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddProjectRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.AddSuperUserResponse TestWsApi.ServiceReference1.GLSysMgrSoap.AddSuperUser(TestWsApi.ServiceReference1.AddSuperUserRequest request) {
            return base.Channel.AddSuperUser(request);
        }
        
        public string AddSuperUser(string strParams) {
            TestWsApi.ServiceReference1.AddSuperUserRequest inValue = new TestWsApi.ServiceReference1.AddSuperUserRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddSuperUserRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.AddSuperUserResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddSuperUser(inValue);
            return retVal.Body.AddSuperUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddSuperUserResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.AddSuperUserAsync(TestWsApi.ServiceReference1.AddSuperUserRequest request) {
            return base.Channel.AddSuperUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddSuperUserResponse> AddSuperUserAsync(string strParams) {
            TestWsApi.ServiceReference1.AddSuperUserRequest inValue = new TestWsApi.ServiceReference1.AddSuperUserRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddSuperUserRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddSuperUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWsApi.ServiceReference1.AddOrgUserResponse TestWsApi.ServiceReference1.GLSysMgrSoap.AddOrgUser(TestWsApi.ServiceReference1.AddOrgUserRequest request) {
            return base.Channel.AddOrgUser(request);
        }
        
        public string AddOrgUser(string strParams) {
            TestWsApi.ServiceReference1.AddOrgUserRequest inValue = new TestWsApi.ServiceReference1.AddOrgUserRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddOrgUserRequestBody();
            inValue.Body.strParams = strParams;
            TestWsApi.ServiceReference1.AddOrgUserResponse retVal = ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddOrgUser(inValue);
            return retVal.Body.AddOrgUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddOrgUserResponse> TestWsApi.ServiceReference1.GLSysMgrSoap.AddOrgUserAsync(TestWsApi.ServiceReference1.AddOrgUserRequest request) {
            return base.Channel.AddOrgUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWsApi.ServiceReference1.AddOrgUserResponse> AddOrgUserAsync(string strParams) {
            TestWsApi.ServiceReference1.AddOrgUserRequest inValue = new TestWsApi.ServiceReference1.AddOrgUserRequest();
            inValue.Body = new TestWsApi.ServiceReference1.AddOrgUserRequestBody();
            inValue.Body.strParams = strParams;
            return ((TestWsApi.ServiceReference1.GLSysMgrSoap)(this)).AddOrgUserAsync(inValue);
        }
    }
}
