//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationLED
{
    using System;
    using System.Collections.Generic;
    
    public partial class ddGasCardInfo
    {
        public int Id { get; set; }
        public string CardName { get; set; }
        public string ProtocolAddr { get; set; }
        public string CardModel { get; set; }
        public Nullable<int> IsDouble { get; set; }
        public Nullable<int> Brightness { get; set; }
        public Nullable<int> PointCount { get; set; }
        public Nullable<int> NumberCount { get; set; }
        public Nullable<int> ScreenCount { get; set; }
        public int CommDevId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public string Context { get; set; }
        public string ScreenNams { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
    }
}
