//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationLED
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public string Address { get; set; }
        public string ManagerName { get; set; }
        public string ManagerTel { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
    }
}
