//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlareSysEfDbAndModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasCardWithCommInfo
    {
        public int Id { get; set; }
        public string DefName { get; set; }
        public string DefPassword { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string CityId { get; set; }
        public string Address { get; set; }
        public string PosLongitude { get; set; }
        public string PosLatitude { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<int> CommType { get; set; }
        public Nullable<int> ProtocolType { get; set; }
        public string CommServerIp { get; set; }
        public Nullable<int> CommServerPort { get; set; }
        public string CommServerSn { get; set; }
        public string CommSerialPort { get; set; }
        public Nullable<int> CommSerialBaud { get; set; }
        public Nullable<int> CommSerialDataBit { get; set; }
        public Nullable<int> CommSerialStopBit { get; set; }
        public Nullable<int> CommSerialParity { get; set; }
        public Nullable<int> CommTimeoutMs { get; set; }
        public string CommExtConnInfo { get; set; }
        public string CardModel { get; set; }
        public Nullable<int> CardIsDouble { get; set; }
        public Nullable<int> CardBrightness { get; set; }
        public Nullable<int> CardPointCount { get; set; }
        public Nullable<int> CardNumberCount { get; set; }
        public Nullable<int> CardScreenCount { get; set; }
        public string CardContext { get; set; }
        public string ScreenNams { get; set; }
        public Nullable<int> BEnable { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IsDel { get; set; }
        public Nullable<System.DateTime> CreateDt { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
    }
}
