//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationLED
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LedDbEntities : DbContext
    {
        public LedDbEntities()
            : base("name=LedDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CityTable_NotDone_todo> CityTable_NotDone_todo { get; set; }
        public DbSet<CmdLogs> CmdLogs { get; set; }
        public DbSet<ddCommDevInfo> ddCommDevInfo { get; set; }
        public DbSet<ddCommDevRealStatus> ddCommDevRealStatus { get; set; }
        public DbSet<ddCommDevStatusLog> ddCommDevStatusLog { get; set; }
        public DbSet<ddCommDevUser> ddCommDevUser { get; set; }
        public DbSet<ddGasCardInfo> ddGasCardInfo { get; set; }
        public DbSet<GasCardRealStatus> GasCardRealStatus { get; set; }
        public DbSet<GasCardStatusLog> GasCardStatusLog { get; set; }
        public DbSet<GasCardWithCommInfo> GasCardWithCommInfo { get; set; }
        public DbSet<GasContextLog> GasContextLog { get; set; }
        public DbSet<GroupInfo> GroupInfo { get; set; }
        public DbSet<GroupUser> GroupUser { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<OrgInfo> OrgInfo { get; set; }
        public DbSet<OrgUser> OrgUser { get; set; }
        public DbSet<ProjectInfo> ProjectInfo { get; set; }
        public DbSet<ProjectUser> ProjectUser { get; set; }
        public DbSet<RoadCardRealStatus> RoadCardRealStatus { get; set; }
        public DbSet<RoadCardStatusLog> RoadCardStatusLog { get; set; }
        public DbSet<RoadTipCardInfo> RoadTipCardInfo { get; set; }
        public DbSet<SuperUser> SuperUser { get; set; }
    }
}
